### ISSUE TITLE
issue with php

### ISSUE THREAD

**Issue by ctf0** [pushqrdx/code-fences#5]
for example i have this in `php` file

```php
/** 
 * ```shell
 * git clone --recurse-submodules ...
 * ```
 */
class CalculationServiceProvider extends ServiceProvider
```

and this in `markdown` file
```shell
git clone --recurse-submodules ...
```

<img width="1530" alt="Screen Shot 2023-02-11 at 5 55 48 AM" src="https://user-images.githubusercontent.com/7388088/218237969-eb1a3100-f2a2-49b9-80fe-168258728697.png">

as u can see, no hl, am i missing something ?

**Comment by pushqrdx** [comment]
there appears to be an issue with highlighting in php documents, the way you usually use this is by opening a block comment and using the same syntax for code blocks as markdown, for instance here is how it looks like highlighting c code in a go file
![image](https://user-images.githubusercontent.com/25884937/218400386-7f11fb9a-c124-4214-9fe1-1508135b7131.png)

and here i am using nested highlighting to highlight c code in a ruby block comment block in a rust file
![image](https://user-images.githubusercontent.com/25884937/218400577-5f907078-4d94-491e-84d5-d82e37ad68d0.png)

I am not sure what's causing the issue with php but i'll try to look into it soon
